import type { Metadata } from "next"
import { Open_Sans } from "next/font/google"  //You can change font style here
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs' //Imported Clerk Provider
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";


const font = Open_Sans({ subsets: ["latin"] })//Also change the function name here

export const metadata: Metadata = {
  title: "Discord-Clone",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body className={cn(font.className , "bg-white dark:bg-[#313338] ")}>
        <ThemeProvider
         attribute="class"
         defaultTheme="dark"
         enableSystem = {false}
         storageKey="disocrd-theme">
        {children}
        </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>
  )
}
